kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  labels:
    disktype: ssd
  extraMounts:
  - hostPath: /moss/home/Projects/kubernetes/files/worker1
    containerPath: /files
    propagation: Bidirectional
- role: worker
  labels:
    gpu: gtx
  extraMounts:
  - hostPath: /moss/home/Projects/kubernetes/files/worker2
    containerPath: /files
    propagation: Bidirectional
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://registry:5000"]